//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFNE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Menu1 = new HashSet<Menu>();
        }
    
        public int Codigo { get; set; }
        public string Tipo { get; set; }
        public string Titulo { get; set; }
        public string Conteudo { get; set; }
        public Nullable<int> CodMenuPai { get; set; }
        public string IdAspNetUsers { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Menu> Menu1 { get; set; }
        public virtual Menu Menu2 { get; set; }
    }
}
