//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFNE.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Menu
    {
        public Menu()
        {
            this.Filhos = new HashSet<Menu>();
        }

        public int Codigo { get; set; }
        public string Tipo { get; set; }
        public string Titulo { get; set; }
        public string Conteudo { get; set; }
        public Nullable<int> CodMenuPai { get; set; }
        public string IdAspNetUsers { get; set; }

        public virtual ICollection<Menu> Filhos { get; set; }
        public virtual Menu Pai { get; set; }
        public virtual ApplicationUser AspNetUser { get; set; }
    }
}
